import { Inter } from "next/font/google";
import "./globals.css";
import dotenv from "dotenv";
import { ToastContainer } from "react-toastify";

dotenv.config();
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
